using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NebBookInterview.Models
{

    //I do not wish to have internal details displayed when queried.
    public class ProductDisplay
    {
        public long? Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        
        public ProductDisplay(Product product)
        {
            Id = product.Id;
            Name = product.Name;
            Price = product.Price;
        }
    }
    
    public class Product
    {
        // key is generated by the DB, so this isn't nullable in the DB, but if passed null will create a new entry
        // private set is used because we want entity framework to be able to set this field on load, but we don't want
        // to ever have our code change it
        [Key]
        public long? Id { get; private set; }
        [MaxLength(50), Required]
        public string Name { get; set; }
        // money is a postgres type that is a fixed point type, generally it will be set to 2 fractional digits
        [Column(TypeName="money")] 
        public decimal Price { get; set; }
        
        public virtual List<ProductPriceChange>? PriceChanges { get; set; }

        public Product(string name, decimal price)
        {
            Name = name;
            Price = price;
        }
        
        
    }
}